ignore-paths:
    - doc
    - examples
    - test
    - utils

pylint:
    max-line-length: 100
    disable:
      - missing-docstring

pyflakes:
  run: false

pep8:
  run: false

mccabe:
  run: false
